import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outFile = path.join(root, "web/eino-workbench/src/contracts/generated.ts");
const checkOnly = process.argv.includes("--check");
const schemaPaths = [
  "docs/schemas/eino_product_facts.v2.schema.json",
  "docs/schemas/eino_query_result_snapshot.v2.schema.json",
  "docs/schemas/eino_workbench_stream_event.v2.schema.json",
  "docs/schemas/eino_workbench_view.v2.schema.json",
  "docs/schemas/tool.structured_result.v2.schema.json"
];

const schemas = schemaPaths.map((schemaPath) => {
  const schema = JSON.parse(fs.readFileSync(path.join(root, schemaPath), "utf8"));
  return { id: schema.$id, title: schema.title, path: schemaPath };
});

const types = `
export type SnapshotItem = {
  readonly snapshot_item_ref: string;
  readonly display_label: string;
  readonly discovered_at: string;
};

export type StructuredResult = {
  readonly schema_version: "tool.structured_result.v2";
  readonly capability_id: "capability.vulnerability.list_new";
  readonly status: "resolved" | "empty";
  readonly query: { readonly kind: "new_vulnerabilities" };
  readonly data: {
    readonly summary: string;
    readonly count: number;
    readonly items: readonly SnapshotItem[];
  };
  readonly metadata: {
    readonly safe: true;
    readonly coverage: "complete_set";
    readonly observed_at: string;
  };
};

export type QueryResultSnapshot = {
  readonly schema_version: "eino_query_result_snapshot.v2";
  readonly snapshot_id: string;
  readonly workspace_id: string;
  readonly conversation_id: string;
  readonly actor_id: string;
  readonly run_id: string;
  readonly tool_call_id: string;
  readonly query_kind: "new_vulnerabilities";
  readonly captured_at: string;
  readonly expires_at: string;
  readonly freshness_version: string;
  readonly coverage: "complete_set";
  readonly items: readonly SnapshotItem[];
};

export type ProductFacts = {
  readonly schema_version: "eino_product_facts.v2";
  readonly workspace_id: string;
  readonly conversation_id: string;
  readonly actor_id: string;
  readonly run_id: string;
  readonly query_sequence: number;
  readonly status: "succeeded" | "failed";
  readonly structured_result: StructuredResult | null;
  readonly snapshot: QueryResultSnapshot | null;
  readonly safe_error?: { readonly code: "fixture_read_failed"; readonly message: string };
  readonly events: readonly {
    readonly event_id: string;
    readonly sequence: number;
    readonly type: "query.succeeded" | "query.failed";
    readonly created_at: string;
  }[];
};

export type M1WorkbenchView = {
  readonly schema_version: "eino_workbench_view.v2";
  readonly workspace_id: string;
  readonly conversation_id: string;
  readonly run_id: string;
  readonly status: "idle" | "running" | "resolved" | "empty" | "failed";
  readonly messages: readonly {
    readonly message_id: string;
    readonly role: "user" | "assistant";
    readonly content: string;
  }[];
  readonly result: {
    readonly query_sequence: number;
    readonly summary: string;
    readonly count: number;
    readonly observed_at: string;
  } | null;
  readonly safe_error?: string;
  readonly right_panel: {
    readonly tabs: readonly ["事实", "执行记录"];
    readonly empty_message: string;
  };
};

export type M1WorkbenchStreamEvent = {
  readonly schema_version: "eino_workbench_stream_event.v2";
  readonly event_id: string;
  readonly run_id: string;
  readonly sequence: number;
  readonly created_at: string;
  readonly type: "view.replaced";
  readonly view: M1WorkbenchView;
};
`;

const body = `// Generated by scripts/eino_workbench_contract_generate.mjs. Do not edit by hand.\nexport type ContractSchema = {\n  readonly id: string;\n  readonly path: string;\n  readonly title: string;\n};\n\nexport const contractSchemas = ${JSON.stringify(schemas, null, 2)} as const satisfies readonly ContractSchema[];\n${types}`;

if (checkOnly) {
  const current = fs.readFileSync(outFile, "utf8");
  if (current !== body) {
    console.error("generated Workbench contract is stale; run npm --prefix web/eino-workbench run contract-generate");
    process.exit(1);
  }
  console.log("generated Workbench contract is current");
} else {
  fs.writeFileSync(outFile, body);
  console.log(`generated ${path.relative(root, outFile)} from ${schemas.length} M1 schemas`);
}
